export type GalleryCategory = 'All' | 'Events';

export type GalleryImage = {
  src: string;
  alt: string;
  category: GalleryCategory;
};

export const galleryImages: GalleryImage[] = [
  { src: '/images/gallery/gallery-img-1.jpeg', alt: 'Gallery Image 1', category: 'Events' },
  { src: '/images/gallery/gallery-img-2.jpeg', alt: 'Gallery Image 2', category: 'Events' },
  { src: '/images/gallery/gallery-img-3.jpeg', alt: 'Gallery Image 3', category: 'Events' },
  { src: '/images/gallery/gallery-img-4.jpeg', alt: 'Gallery Image 4', category: 'Events' },
  { src: '/images/gallery/gallery-img-5.jpeg', alt: 'Gallery Image 5', category: 'Events' },
  { src: '/images/gallery/gallery-img-6.jpeg', alt: 'Gallery Image 6', category: 'Events' },
  { src: '/images/gallery/gallery-img-7.jpeg', alt: 'Gallery Image 7', category: 'Events' },
  { src: '/images/gallery/gallery-img-8.jpeg', alt: 'Gallery Image 8', category: 'Events' },
  { src: '/images/gallery/gallery-img-9.jpeg', alt: 'Gallery Image 9', category: 'Events' },
  { src: '/images/gallery/gallery-img-10.jpeg', alt: 'Gallery Image 10', category: 'Events' },
  { src: '/images/gallery/gallery-img-11.jpeg', alt: 'Gallery Image 11', category: 'Events' },
  { src: '/images/gallery/gallery-img-12.jpeg', alt: 'Gallery Image 12', category: 'Events' },
  { src: '/images/gallery/gallery-img-13.jpeg', alt: 'Gallery Image 13', category: 'Events' },
  { src: '/images/gallery/gallery-img-14.jpeg', alt: 'Gallery Image 14', category: 'Events' },
  { src: '/images/gallery/gallery-img-15.jpeg', alt: 'Gallery Image 15', category: 'Events' },
  { src: '/images/gallery/gallery-img-16.jpeg', alt: 'Gallery Image 16', category: 'Events' },
  { src: '/images/gallery/gallery-img-17.jpeg', alt: 'Gallery Image 17', category: 'Events' },
  { src: '/images/gallery/gallery-img-18.jpeg', alt: 'Gallery Image 18', category: 'Events' },
  { src: '/images/gallery/gallery-img-19.jpeg', alt: 'Gallery Image 19', category: 'Events' },
  { src: '/images/gallery/gallery-img-20.jpeg', alt: 'Gallery Image 20', category: 'Events' },
  { src: '/images/gallery/gallery-img-21.jpeg', alt: 'Gallery Image 21', category: 'Events' },
  { src: '/images/gallery/gallery-img-22.jpeg', alt: 'Gallery Image 22', category: 'Events' },
  { src: '/images/gallery/gallery-img-23.jpeg', alt: 'Gallery Image 23', category: 'Events' },
  { src: '/images/gallery/gallery-img-24.jpeg', alt: 'Gallery Image 24', category: 'Events' },
  { src: '/images/gallery/gallery-img-25.jpeg', alt: 'Gallery Image 25', category: 'Events' },
  { src: '/images/gallery/gallery-img-26.jpeg', alt: 'Gallery Image 26', category: 'Events' },
  { src: '/images/gallery/gallery-img-27.jpeg', alt: 'Gallery Image 27', category: 'Events' },
  { src: '/images/gallery/gallery-img-28.jpeg', alt: 'Gallery Image 28', category: 'Events' },
  { src: '/images/gallery/gallery-img-29.jpeg', alt: 'Gallery Image 29', category: 'Events' },
  { src: '/images/gallery/gallery-img-30.jpeg', alt: 'Gallery Image 30', category: 'Events' },
  { src: '/images/gallery/gallery-img-31.jpeg', alt: 'Gallery Image 31', category: 'Events' },
  { src: '/images/gallery/gallery-img-32.jpeg', alt: 'Gallery Image 32', category: 'Events' },
  { src: '/images/gallery/gallery-img-33.jpeg', alt: 'Gallery Image 33', category: 'Events' },
  { src: '/images/gallery/gallery-img-34.jpeg', alt: 'Gallery Image 34', category: 'Events' },
  { src: '/images/gallery/gallery-img-35.jpeg', alt: 'Gallery Image 35', category: 'Events' },
  { src: '/images/gallery/gallery-img-36.jpeg', alt: 'Gallery Image 36', category: 'Events' },
  { src: '/images/gallery/gallery-img-37.jpeg', alt: 'Gallery Image 37', category: 'Events' },
  { src: '/images/gallery/gallery-img-38.jpeg', alt: 'Gallery Image 38', category: 'Events' },
  { src: '/images/gallery/gallery-img-39.jpeg', alt: 'Gallery Image 39', category: 'Events' },
  { src: '/images/gallery/gallery-img-40.jpeg', alt: 'Gallery Image 40', category: 'Events' },
  { src: '/images/gallery/gallery-img-41.jpeg', alt: 'Gallery Image 41', category: 'Events' },
  { src: '/images/gallery/gallery-img-42.jpeg', alt: 'Gallery Image 42', category: 'Events' },
  { src: '/images/gallery/gallery-img-43.jpeg', alt: 'Gallery Image 43', category: 'Events' },
  { src: '/images/gallery/gallery-img-44.jpeg', alt: 'Gallery Image 44', category: 'Events' },
  { src: '/images/gallery/gallery-img-45.png', alt: 'Gallery Image 45', category: 'Events' },
  { src: '/images/gallery/gallery-img-46.jpeg', alt: 'Gallery Image 46', category: 'Events' },
  { src: '/images/gallery/gallery-img-47.jpeg', alt: 'Gallery Image 47', category: 'Events' },
  { src: '/images/gallery/gallery-img-48.jpeg', alt: 'Gallery Image 48', category: 'Events' },
  { src: '/images/gallery/gallery-img-49.jpeg', alt: 'Gallery Image 49', category: 'Events' },
  { src: '/images/gallery/gallery-img-50.jpeg', alt: 'Gallery Image 50', category: 'Events' },
  { src: '/images/gallery/gallery-img-51.jpeg', alt: 'Gallery Image 51', category: 'Events' },
  { src: '/images/gallery/gallery-img-52.jpeg', alt: 'Gallery Image 52', category: 'Events' },
  { src: '/images/gallery/gallery-img-53.jpeg', alt: 'Gallery Image 53', category: 'Events' },
  { src: '/images/gallery/gallery-img-54.jpeg', alt: 'Gallery Image 54', category: 'Events' },
  { src: '/images/gallery/gallery-img-55.jpeg', alt: 'Gallery Image 55', category: 'Events' },
  { src: '/images/gallery/gallery-img-56.jpeg', alt: 'Gallery Image 56', category: 'Events' },
  { src: '/images/gallery/gallery-img-57.jpeg', alt: 'Gallery Image 57', category: 'Events' },
  { src: '/images/gallery/gallery-img-58.jpeg', alt: 'Gallery Image 58', category: 'Events' },
  { src: '/images/gallery/gallery-img-59.jpeg', alt: 'Gallery Image 59', category: 'Events' },
  { src: '/images/gallery/gallery-img-60.jpeg', alt: 'Gallery Image 60', category: 'Events' },
  { src: '/images/gallery/gallery-img-61.jpeg', alt: 'Gallery Image 61', category: 'Events' },
  { src: '/images/gallery/gallery-img-62.jpeg', alt: 'Gallery Image 62', category: 'Events' },
  { src: '/images/gallery/gallery-img-63.jpeg', alt: 'Gallery Image 63', category: 'Events' },
  { src: '/images/gallery/gallery-img-64.jpeg', alt: 'Gallery Image 64', category: 'Events' },
  { src: '/images/gallery/gallery-img-65.jpeg', alt: 'Gallery Image 65', category: 'Events' },
  { src: '/images/gallery/gallery-img-66.jpeg', alt: 'Gallery Image 66', category: 'Events' },
  { src: '/images/gallery/gallery-img-67.jpeg', alt: 'Gallery Image 67', category: 'Events' },
];
